In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#reading the data set
#here we are loading the data from scklit learn
from sklearn.datasets import load_diabetes
load_diabetes_dataset = load_diabetes()

In [ ]:
data = pd.DataFrame(load_diabetes_dataset.data,columns=load_diabetes_dataset.feature_names)
data.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [ ]:
# Problem statement : To Predict disease progration one year after basline provides 10 features

In [ ]:
print(load_diabetes_dataset.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

In [ ]:
data.head

<bound method NDFrame.head of           age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
..        ...       ...       ...       ...       ...       ...       ...
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

           s4        s5        s6
0   -0.002592  0.019907 -0.017646
1   -0.039493 -0.068332 -0.092204
2   -0.002592  0.002861 -0.025930
3    0.034309  0.022688 -0.009362
4   -0.002592 -0.031988 -0.046641
..        ...       ...       ...
437 -0.002592  0.031193  0.007207
438  0.034309 -0.018114  0.044485
439 -0.011080 -0.046883  0.015491
440  0.026560  0.044529 -0.025930
441 -0.039493 -0.004222  0.003064

[442 rows x 10 columns]>

In [ ]:
data['target'] = load_diabetes_dataset.target

In [ ]:
#eda , data prepration , feature)enginnering

In [ ]:
x = data [["bmi"]]
y = data[["target"]]

In [ ]:
x

          bmi
0    0.061696
1   -0.051474
2    0.044451
3   -0.011595
4   -0.036385
..        ...
437  0.019662
438 -0.015906
439 -0.015906
440  0.039062
441 -0.073030

[442 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_test_split(x,y,test_size=0.2,random_state=42)

[          bmi
 17   0.012117
 66  -0.018062
 137  0.049840
 245 -0.035307
 31  -0.065486
 ..        ...
 106 -0.076264
 270  0.030440
 348 -0.020218
 435 -0.023451
 102  0.028284

 [353 rows x 1 columns],
           bmi
 287 -0.006206
 211  0.036907
 72  -0.004050
 321  0.051996
 73  -0.020218
 ..        ...
 255 -0.065486
 90  -0.025607
 57  -0.063330
 391 -0.069797
 24   0.035829

 [89 rows x 1 columns],
      target
 17    144.0
 66    150.0
 137   280.0
 245   125.0
 31     59.0
 ..      ...
 106   134.0
 270   202.0
 348   148.0
 435    64.0
 102   302.0

 [353 rows x 1 columns],
      target
 287   219.0
 211    70.0
 72    202.0
 321   230.0
 73    111.0
 ..      ...
 255   153.0
 90     98.0
 57     37.0
 391    63.0
 24    184.0

 [89 rows x 1 columns]]

In [ ]:
x_train, x_test , y_train, y_test =